version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: gestao-backend
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./frontend
    container_name: gestao-frontend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: gestao-nginx
    ports:
      - "4200:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
