version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${HOME_PATH}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PORT_MACHINE_PROMETHEUS}:9090"
    networks:
      - observability-net
    restart: unless-stopped

  loki:
    image: grafana/loki
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "${PORT_MACHINE_LOKI}:3100"
    networks:
      - observability-net
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "${PORT_FRONTEND_TEMPO}:3200"
      - "${PORT_SEND_TRACES_TEMPO}:4318"
    volumes:
      - ${HOME_PATH}/tempo/tempo-config.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    networks:
      - observability-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3200/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${PORT_MACHINE_GRAFANA}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - observability-net
      - management-net
    restart: unless-stopped

volumes:
  grafana_data:
  tempo_data:

networks:
  observability-net:
    external: true
  management-net:
    external: true