version: '3.8'

services:
  backend:
    image: ghcr.io/seu-usuario/seu-repositorio-backend:tag-a-definir # TODO: substitua com a imagem correta
    container_name: gestao-backend
    ports:
      - "${PORT_MACHINE_BACKEND}:${PORT_CONTAINER_BACKEND}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    image: ghcr.io/seu-usuario/seu-repositorio-frontend:tag-a-definir # TODO: substitua com a imagem correta
    container_name: gestao-frontend
    ports:
      - "${PORT_MACHINE_FRONTEND}:${PORT_CONTAINER_FRONTEND}"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: gestao-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT_MACHINE_POSTGRES}:${PORT_CONTAINER_POSTGRES}"

volumes:
  postgres_data:
