version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: gestao-backend
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  frontend:
    build:
      context: ./frontend
      args:
        ENV_FILE: .env.development
    container_name: gestao-frontend
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: gestao-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: gestao-nginx
    ports:
      - "4200:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
