version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: gestao-backend
    ports:
      - "${PORT_MACHINE_BACKEND}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend
    container_name: gestao-frontend
    ports:
      - "${PORT_MACHINE_FRONTEND}:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: gestao-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT_MACHINE_POSTGRES}:5432"
volumes:
  postgres_data:
