namespace gestaotcc.Domain.Enums;

public enum StepTccType
{
    PROPOSAL_REGISTRATION = 1,
    START_AND_ORGANIZATION = 2,
    DEVELOPMENT_AND_MONITORING = 3,
    PREPARATION_FOR_PRESENTATION = 4,
    PRESENTATION_AND_EVALUATION = 5,
    FINALIZATION_AND_PUBLICATION = 6
}