name: Development Workflow

on :
  push:
    branches:
      - development
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - development
    paths:
      - 'frontend/**'
      - 'backend/**'
      
jobs:
  frontend:
    name: Frontend Development
    runs-on: ubuntu-latest
    # Adicionar condição para rodar apenas se houver alterações no frontend

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          cd frontend
          npm install

      - name: Rodar Lint
        run: |
          cd frontend
          npm run lint

      - name: Buildar Frontend
        run: |
          cd frontend
          npm run build

  backend:
    name: Backend Development
    runs-on: ubuntu-latest
    # Adicionar condição para rodar apenas se houver alterações no backend

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restaurar dependências
        run: |
          cd backend
          dotnet restore

      - name: Buildar Backend
        run: |
          cd backend
          dotnet build --configuration Release

      - name: Rodar Testes
        run: echo "Nenhum teste implementado ainda."
