name: CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/gestao-frontend:latest -f Dockerfile .

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Scan image for critical vulnerabilities
        run: |
          docker scout cves ghcr.io/${{ github.repository_owner }}/gestao-frontend:latest --only-severity critical --exit-code 1 || exit 0

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/gestao-frontend:latest

  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Lint with dotnet format
        run: dotnet format --verify-no-changes --verbosity detailed

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/gestao-backend:latest -f Dockerfile .

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Scan image for critical vulnerabilities
        run: |
          docker scout cves ghcr.io/${{ github.repository_owner }}/gestao-backend:latest --only-severity critical --exit-code 1 || exit 0

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/gestao-backend:latest
